= Final proyect and documentation
Yael Mata Olmos <MataKnows1208@gmail.com>
:doctype: book
:toc: 
:imagesdir: Images
:sectnums: 
:toclevels: 3
:chapter-label: Section

== Project description

This software allows the user to deploy two microcontrollers at the same time capable of performing multiple tasks using the command-response format.
It has been developed with the Actor Framework and with the use of new tools recently seen in classes such as HAL, SSC, etc.

== Code component descriptions

=== DQMH(R) modules

This section describes DQMH(R) module responsibilities and relationships.

==== Preamble

A DQMH module is the main component of an architecture based on DQMH(R) framework. A DQMH module is used to implement a section of the application that has one responsibility.

DQMH(R) framework defines two different type of DQMH module.  

====
*Singleton:*

A Singleton DQMH module can have only one instance running at any given time.
====

====
*Cloneable:*

A Cloneable DQMH module can have one or multiple instances running in parallel.
====

DQMH(R) framework defines two different ways to carry data throughout the application and with both other DQMH modules and non-DQMH based code.

====
*Request events:*

A request is a code that fires an event requesting the DQMH module to do something. Multiple locations in the code can send events to the DQMH module.

Request events are many-to-one.

Requests are usually named using imperative tense.
====

====
*Broadcast events:*

A broadcast is a code that fires an event broadcasting that the DQMH module did something. Multiple Event Structures can register to handle the Broadcast Events.

Broadcast Events are one-to-many.

Broadcasts are usually named using past tense or passive voice.
====

NOTE: Refer to the DQMH(R) framework official http://delacor.com/documentation/dqmh-html/[documentation] to find more details on how the framework works


The following section gives you details on the project architecture relying on this framework.
It gives you an overview of the modules' interaction and detailed information on each module.

Graphs used in this section have the following legend:

*Components:*


[graphviz, format="png", align="center"]
....
digraph G8953 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"DQMH module / Lvlib"[color=black shape=component]
"Vi"[color=skyblue shape=note]
}
....

*Events:*

[graphviz, format="png", align="center"]
....
digraph G52487 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
" "[color=white shape=box]
"  "[color=white shape=box]
"   "[color=white shape=box]
"    "[color=white shape=box]
" " -> "  " [label="Request to a DQMH module" dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1];
"   " -> "    " [label="Broadcast from a DQMH module" dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1];
}
....

*Start and Stop module callers:*

[graphviz, format="png", align="center"]
....
digraph G279155 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Start Module
caller"[color=black shape=component]
"Start Module"[color=yellowgreen shape=note]
"Start Module" -> "Start Module
caller" [label="Called by" dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1];
}
....

[graphviz, format="png", align="center"]
....
digraph G707861 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
"Stop Module
caller"[color=black shape=component]
"Stop Module"[color=tomato shape=note]
"Stop Module" -> "Stop Module
caller" [label="Called by" dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1];
}
....


==== Modules overview

This project contains the following modules.

.Modules list
|===
|Singleton|Cloneable

|===

This graph represents the links between all DQMH modules.

[graphviz, format="png", align="center"]
....
digraph G616167 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1]
node[color=black shape=box]
}
....


=== Libraries

This section describes the libraries contained in the project.

==== UI Actor.lvlib

The UI Actor is the user interface that is displayed after choosing through the launcher with which of the two microcontrollers we want to operate. It contains the main commands with which we operate the microcontrollers and through its actor messages we have been able to link the AF with the project and HAL.


=== Classes

This section describes the classes contained in the project.

==== Test ADC command.lvclass

The ADC Command Test is a unit test in which we take one of the simulated devices and separate its commands into fractions to ensure step by step that there are no errors, if there is any, the unit test will let us know so we can immediately correct it. and test until the code is correct.


==== visa Init Msg.lvclass

No description found (add content in lvlib description)


==== UI Actor.lvclass

In the UI Actor class we can find the user interface in the actor core, while the events generated by the syndicators go towards the Pre-Launch Init
We also have the vi called visa Init in which we make the initial configuration with which we can later start working on serial devices.


== VI descriptions

=== DQMH(R) modules

This section describes DQMH(R) modules events.

=== Libraries

This section describes libraries public VIs.

==== UI Actor.lvlib

===== UI Actor.lvlib:visa Init Msg.lvclass:Send visa Init.vi

:imgpath: UI Actor.lvlib_visa Init Msg.lvclass_Send visa Init.vi.png
image::{imgpath}[UI Actor.lvlib:visa Init Msg.lvclass:Send visa Init.vi]

*Description:*
++++
This VI sends the message to an actor.
++++

===== UI Actor.lvlib:visa Init Msg.lvclass:Do.vi

:imgpath: UI Actor.lvlib_visa Init Msg.lvclass_Do.vi.png
image::{imgpath}[UI Actor.lvlib:visa Init Msg.lvclass:Do.vi]

*Description:*
++++
This VI delivers the message to the actor by calling the appropriate method(s) on the actor.
++++

===== UI Actor.lvlib:UI Actor.lvclass:Read Serial Device.lvclass.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Read Serial Device.lvclass.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Read Serial Device.lvclass.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:Write Serial Device.lvclass.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Write Serial Device.lvclass.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Write Serial Device.lvclass.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:Read VISA resource name.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Read VISA resource name.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Read VISA resource name.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:Write VISA resource name.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Write VISA resource name.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Write VISA resource name.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:Launcher.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Launcher.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Launcher.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:visa Init.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_visa Init.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:visa Init.vi]

*Description:*
No description found (add content in VI description)

=== Classes

This section describes classes public VIs.

==== Test ADC command.lvclass

===== Test ADC command.lvclass:setUp.vi

:imgpath: Test ADC command.lvclass_setUp.vi.png
image::{imgpath}[Test ADC command.lvclass:setUp.vi]

*Description:*
++++
setUp runs prior to the test method during test execution.  Use this method to initialize any object data required by your tests.
++++

===== Test ADC command.lvclass:tearDown.vi

:imgpath: Test ADC command.lvclass_tearDown.vi.png
image::{imgpath}[Test ADC command.lvclass:tearDown.vi]

*Description:*
++++
tearDown runs after the test method has completed.  Use this method to clean up any operations or references that were opened by setUp or the test method.  Unit tests should be independent of other unit tests so this VI should ensure that the next test can run in a 'clean' test environment.
++++

===== Test ADC command.lvclass:testExample.vit

:imgpath: Test ADC command.lvclass_testExample.vit.png
image::{imgpath}[Test ADC command.lvclass:testExample.vit]

*Description:*
No description found (add content in VI description)

===== Test ADC command.lvclass:temp_VI_UnderTest.vi

:imgpath: Test ADC command.lvclass_temp_VI_UnderTest.vi.png
image::{imgpath}[Test ADC command.lvclass:temp_VI_UnderTest.vi]

*Description:*
No description found (add content in VI description)

===== Test ADC command.lvclass:Test ADC command testing.vi

:imgpath: Test ADC command.lvclass_Test ADC command testing.vi.png
image::{imgpath}[Test ADC command.lvclass:Test ADC command testing.vi]

*Description:*
No description found (add content in VI description)

==== visa Init Msg.lvclass

===== UI Actor.lvlib:visa Init Msg.lvclass:Send visa Init.vi

:imgpath: UI Actor.lvlib_visa Init Msg.lvclass_Send visa Init.vi.png
image::{imgpath}[UI Actor.lvlib:visa Init Msg.lvclass:Send visa Init.vi]

*Description:*
++++
This VI sends the message to an actor.
++++

===== UI Actor.lvlib:visa Init Msg.lvclass:Do.vi

:imgpath: UI Actor.lvlib_visa Init Msg.lvclass_Do.vi.png
image::{imgpath}[UI Actor.lvlib:visa Init Msg.lvclass:Do.vi]

*Description:*
++++
This VI delivers the message to the actor by calling the appropriate method(s) on the actor.
++++

==== UI Actor.lvclass

===== UI Actor.lvlib:UI Actor.lvclass:Read Serial Device.lvclass.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Read Serial Device.lvclass.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Read Serial Device.lvclass.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:Write Serial Device.lvclass.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Write Serial Device.lvclass.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Write Serial Device.lvclass.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:Read VISA resource name.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Read VISA resource name.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Read VISA resource name.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:Write VISA resource name.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Write VISA resource name.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Write VISA resource name.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:Launcher.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_Launcher.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:Launcher.vi]

*Description:*
No description found (add content in VI description)

===== UI Actor.lvlib:UI Actor.lvclass:visa Init.vi

:imgpath: UI Actor.lvlib_UI Actor.lvclass_visa Init.vi.png
image::{imgpath}[UI Actor.lvlib:UI Actor.lvclass:visa Init.vi]

*Description:*
No description found (add content in VI description)

== Legal Information

=== Document creation

This document has been generated using the following tools.

==== Antidoc

Project website: https://wovalab.gitlab.io/open-source/labview-doc-generator/[Antidoc] 

Maintainer website: https://wovalab.com[Wovalab] 

BSD 3-Clause License

Copyright (C) 2019, Wovalab,
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


==== Asciidoc for LabVIEW(TM)

Project website: https://wovalab.gitlab.io/open-source/asciidoc-toolkit/[Asciidoc toolkit] 

Maintainer website: https://wovalab.com[Wovalab] 

BSD 3-Clause License

Copyright (C) 2019, Wovalab,
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


==== Graph Builder

Project website: https://gitlab.com/cgambini/graph-builder[Graph Builder]

BSD 3-Clause License

Copyright (c) 2020, Cyril GAMBINI
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


=== Product used in the project

Antidoc hasn't been able to detect third party products in the project.
This is the author's responsibility to list any of the missing product used.
